### ISSUE TITLE
Simplify lateral menu

### ISSUE THREAD

**Issue by rowsky** [borgia-app/Borgia#66]
## Simplify lateral menu
The menu contains some unnecessary submenus.
- Submenus with only Add and List links are not relevant.

**Comment by GuillaumeBroggi** [comment]
Example:
<img width="241" alt="screen shot 2018-05-27 at 18 01 51" src="https://user-images.githubusercontent.com/25569517/40588065-359fc4ba-61d8-11e8-9851-19db1bc549c2.png">

How do we solve it?
1. Direct access to the functionality instead of a submenu
Or
2. Integrate Add and List links directly on main menu
