### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#9]
It seems that it doesn't work. 

Documentation is also needed.

**Comment by AlexandrePalo** [comment]
This feature does work for Siber's with the email address: ae.ensam.assoc@gmail.com
I'll check with Birse with this address and another one.

**Comment by AlexandrePalo** [comment]
Does work for Birse too with borgiabirse@gmail.com
I sent a message to Sebastien at Birse. I'm waiting for his response.

**Comment by AlexandrePalo** [comment]
After exploring, no issue found.
I close this   @#issue for the moment.

**Comment by AlexandrePalo** [comment]
Closed for the moment.

**Comment by AlexandrePalo** [comment]
## Reopen!

The issue was that you can't reset a password if no password is set (ie. `user.password = ''`).
To solve the issue, change the password to a new one (for instance a random one) by the shell and ask for a reset.

`"".join(choice(string.ascii_letters) for x in range(randint(30, 40)))` to generate random string letters between 30 and 40 letters.
